#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

// this should use space cadet shift
/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


// defines that add overhead to the split communication protocol, negatively impact matrix scan speed
// #define SPLIT_TRANSPORT_MIRROR  //

typedef enum {
    TD_NONE,
    TD_UNKNOWN,
    TD_SINGLE_TAP,
    TD_SINGLE_HOLD,
    TD_DOUBLE_TAP,
    TD_DOUBLE_HOLD,
    TD_DOUBLE_SINGLE_TAP, // useful to send two single taps
    TD_TRIPLE_TAP,
    TD_TRIPLE_HOLD
} td_state_t;

typedef struct {
    bool is_press_action;
    td_state_t state;
} td_tap_t;

typedef enum  {
    DANCE1
} tap_dance_keycodes;

td_state_t cur_dance(tap_dance_state_t *state);
void dance1_finished(tap_dance_state_t *state, void *user_data);
void dance1_reset(tap_dance_state_t *state, void *user_data);

// Layouts
typedef enum  {
    _QUERTY,
    _GAME,
    _SYMBOL,
    _ADJUST
} layer_names;

// shorter keycodes 
#define LEFTALT LALT_T(KC_LBRC)
#define RIGHTALT RALT_T(KC_RBRC)
#define TD_1 TD(DANCE1)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_QUERTY] = LAYOUT(
    // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
        QK_GESC ,  KC_1  ,  KC_2  ,  KC_3  ,  KC_4  ,  KC_5  ,                             KC_6  ,  KC_7  ,  KC_8  ,  KC_9  ,  KC_0  , KC_BSPC,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
         KC_TAB ,  KC_Q  ,  KC_W  ,  KC_E  ,  KC_R  ,  KC_T  ,                             KC_Y  ,  KC_U  ,  KC_I  ,  KC_O  ,  KC_P  , KC_ENT ,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
         SC_LSPO,  KC_A  ,  KC_S  ,  KC_D  ,  KC_F  ,  KC_G  ,                             KC_H  ,  KC_J  ,  KC_K  ,  KC_L  , KC_SCLN, SC_RSPC,
    // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
         KC_LCTL,  KC_Z  ,  KC_X  ,  KC_C  ,  KC_V  ,  KC_B  , LEFTALT,         RIGHTALT,  KC_N  ,  KC_M  , KC_COMM, KC_DOT , KC_SLSH, KC_QUOT,
    // └────────┴────────┴────────┴────┬───┴────┬───┴────┬───┴────┬───┘        └────┬───┴────┬───┴────┬───┴────┬───┴────────┴────────┴────────┘
                                         KC_LGUI,MO(_SYMBOL), KC_SPC ,                  KC_SPC,    TD_1  , KC_ENT
                                    // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    ),
    [_SYMBOL] = LAYOUT(
    // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
        KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
        KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_LPRN, KC_RPRN, KC_AMPR, KC_P1, KC_P2, KC_P3, KC_EQL, KC_TRNS,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
       KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_LCBR, KC_RCBR, KC_PIPE, KC_P4, KC_P5, KC_P6, KC_MINS, KC_TRNS,
    // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
       KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_EXLM, KC_P7, KC_P8, KC_P9, KC_BSLS, KC_TRNS,
    // └────────┴────────┴────────┴────┬───┴────┬───┴────┬───┴────┬───┘        └────┬───┴────┬───┴────┬───┴────┬───┴────────┴────────┴────────┘
                                        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P0
                                    // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    ),
    [_GAME] = LAYOUT(
    // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
       KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
       KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_ENT,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
        KC_LSFT,KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, RGB_VAI, RGB_VAD, 
    // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
        KC_LCTL,KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LALT, KC_NO, KC_N, KC_M, RGB_TOG, BL_TOGG, BL_UP, BL_DOWN,
    // └────────┴────────┴────────┴────┬───┴────┬───┴────┬───┴────┬───┘        └────┬───┴────┬───┴────┬───┴────┬───┴────────┴────────┴────────┘
                                       KC_LGUI, KC_SPC, KC_F1, KC_CAPS, TD_1, KC_NO
                                    // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    ),
    [_ADJUST] = LAYOUT(
    // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
         QK_BOOT, EE_CLR , KC_PWR , KC_SLEP, KC_WAKE, KC_NO  ,                            KC_NO  , KC_WAKE, KC_SLEP, KC_PWR , EE_CLR , QK_BOOT,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
         KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  ,                            KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  ,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
         KC_NO  , KC_NO  , NK_TOGG, KC_NO  , KC_NO  , RGB_TOG,                            RGB_TOG, KC_NO  , NK_TOGG, KC_NO  , KC_NO  , KC_NO  ,
    // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
         KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  ,          KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  ,
    // └────────┴────────┴────────┴────┬───┴────┬───┴────┬───┴────┬───┘        └────┬───┴────┬───┴────┬───┴────┬───┴────────┴────────┴────────┘
                                         KC_NO  ,  TD_1  , KC_NO  ,                    KC_NO ,  TD_1  , KC_NO
                                    // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    )

    /*
    [_EMPTY] = LAYOUT(
    // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
                ,        ,        ,        ,        ,        ,                                   ,        ,        ,        ,        ,        ,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
                ,        ,        ,        ,        ,        ,                                   ,        ,        ,        ,        ,        ,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
                ,        ,        ,        ,        ,        ,                                   ,        ,        ,        ,        ,        ,
    // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
                ,        ,        ,        ,        ,        ,        ,                 ,        ,        ,        ,        ,        ,        ,
    // └────────┴────────┴────────┴────┬───┴────┬───┴────┬───┴────┬───┘        └────┬───┴────┬───┴────┬───┴────┬───┴────────┴────────┴────────┘
                                                ,        ,        ,                          ,        ,
                                    // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    ),
    */
};


/* RGB SECTION */
uint8_t leds_numpad[] = {44, 45, 46, 51, 52, 53, 56, 57,59, 63};
uint8_t leds_function[] = {0, 2, 3, 5, 6, 8, 34, 36, 37, 39, 40, 42};
uint8_t leds_wasd[] = {12, 16, 17, 18};
// uint8_t leds_settings[] = {};
// uint8_t leds_warning[] = {0, 1, 2, 3, 4, 34, 35, 36, 37, 38};
uint8_t leds_backlight[] = {1, 4, 7, 24, 27, 31, 35, 38, 41, 58, 61, 65};

   // set initial rgb here or in default_layer_state_set_user(layer_state_t state)???
void keyboard_post_init_user(void) {
   (void) rgb_matrix_enable_noeeprom();
}

// uint8_t leds_numpad[] = {};
// uint8_t leds_function[] = {};
// uint8_t leds_wasd[] = {};
// uint8_t leds_settings[] = {};
// uint8_t leds_warning[] = {};

// layer indicator on all keys
bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    // for (uint8_t i = led_min; i < led_max; i++) {
        switch(get_highest_layer(layer_state|default_layer_state)) {
            case _QUERTY:
                // rgb_matrix_mode(RGB_MATRIX_CUSTOM_my_cool_effect);
                // set my favorite custom effect here
                (void)rgb_matrix_set_color_all(RGB_PURPLE);
                // rgblight_setrgb (0x00,  0x00, 0xFF);
                break;
            case _SYMBOL:
                // highlight numpad, function row, and arrow keys
                (void)rgb_matrix_set_color_all(RGB_BLUE);
                break;
            case _GAME:
                // highlight wasd, and can use effect on any others
                (void)rgb_matrix_set_color_all(RGB_YELLOW);
                break;
            case _ADJUST:
                // no effect on main rgb, pulsing effect on backlight.
                // highlight reset key, any other important keys
                (void)rgb_matrix_set_color_all(RGB_GREEN);
                break;
            default:
                break;
        }
    // }
    return false;
}

// when using WS2812 hsv is important because it allows the brightness to be limited

// uint32_t layer_state_set_user(uint32_t state) {
//     uint8_t layer = biton32(state);
//     switch(layer){
//         case _QUERTY: // 0-th layer
//         break;
//         case
//     }
// }


/* TAP DANCE SECTION */

// look here for inspiration: https://github.com/walkerstop/qmk_firmware/blob/fanoe/keyboards/wheatfield/blocked65/keymaps/walker/keymap.c
td_state_t cur_dance(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (!state->pressed)  //state->interrupted ||
            return TD_SINGLE_TAP;
        // Key has not been interrupted, but the key is still held. Means you want to send a 'HOLD'.
        else
            return TD_SINGLE_HOLD;
    } else if (state->count == 2) {
        // TD_DOUBLE_SINGLE_TAP is to distinguish between typing "pepper", and actually wanting a double tap
        // action when hitting 'pp'. Suggested use case for this return value is when you want to send two
        // keystrokes of the key, and not the 'double tap' action/macro.
        // if (state->interrupted) return TD_DOUBLE_SINGLE_TAP;
        // else if (state->pressed) return TD_DOUBLE_HOLD;
        // else
         return TD_DOUBLE_TAP;
    }

    // Assumes no one is trying to type the same letter three times (at least not quickly).
    // If your tap dance key is 'KC_W', and you want to type "www." quickly - then you will need to add
    // an exception here to return a 'TD_TRIPLE_SINGLE_TAP', and define that enum just like 'TD_DOUBLE_SINGLE_TAP'
    // if (state->count == 3) {
    //     if (state->interrupted || !state->pressed) return TD_TRIPLE_TAP;
    //     else return TD_TRIPLE_HOLD;
    // }
    else if (state->count == 3) {
        if (state->interrupted || !state->pressed) return TD_TRIPLE_TAP;
        else return TD_TRIPLE_HOLD;
    }
    else return TD_UNKNOWN;
}

// Create an instance of 'td_tap_t' for the 'dance1' tap dance.
static td_tap_t dance1_tap_state = {
    .is_press_action = true,
    .state = TD_NONE
};

void dance1_finished(tap_dance_state_t *state, void *user_data) {
    dance1_tap_state.state = cur_dance(state);
    switch (dance1_tap_state.state) {
        case TD_SINGLE_TAP:
            // one shot mod to symbol layer
            set_oneshot_layer(_SYMBOL, ONESHOT_START);
            clear_oneshot_layer_state(ONESHOT_PRESSED);
            break;
        case TD_DOUBLE_TAP:
            switch(get_highest_layer(layer_state|default_layer_state)) {
                case _QUERTY:
                    layer_move(_GAME);
                    break;
                case _GAME:
                    layer_move(_QUERTY);
                    break;
                default:
                    layer_move(_QUERTY);
                    break;
            }
            break;
        case TD_TRIPLE_TAP:
            layer_move(_ADJUST);
            break;
        // Last case is for fast typing. Assuming your key is `f`:
        // For example, when typing the word `buffer`, and you want to make sure that you send `ff` and not `Esc`.
        // In order to type `ff` when typing fast, the next character will have to be hit within the `TAPPING_TERM`, which by default is 200ms.
        // case TD_DOUBLE_SINGLE_TAP: tap_code(KC_Z); register_code(KC_Z); break; // nothing
        default: break;
    }
}

void dance1_reset(tap_dance_state_t *state, void *user_data) {
    switch (dance1_tap_state.state) {
        case TD_SINGLE_TAP: break; // do nothing
        case TD_DOUBLE_TAP: break; // do nothing
        case TD_TRIPLE_TAP: break; // do nothing
        default: break;
    }
    dance1_tap_state.state = TD_NONE;
}

// Tap Dance definitions, to access use the TD(index) macro in layouts
tap_dance_action_t tap_dance_actions[] = {
    [DANCE1] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, dance1_finished, dance1_reset)
};
