#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

// this should use space cadet shift
/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


// defines that add overhead to the split communication protocol, negatively impact matrix scan speed
#define SPLIT_TRANSPORT_MIRROR  // 




const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT( //QUERTY
        QK_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_ENT, LSFT_T(KC_LCBR), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, RSFT_T(KC_RCBR), KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, LALT_T(KC_LBRC), RALT_T(KC_RBRC), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_QUOT, KC_LGUI, MO(1), KC_SPC, KC_SPC, TO(2), KC_ENT
    ),
//     [_EMPTY] = LAYOUT_kc(
//     // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
//         QK_GESC ,  KC_1  ,  KC_2  ,  KC_3  ,  KC_4  ,  KC_5  ,                             KC_6  ,  KC_7  ,  KC_8  ,        ,        ,        ,
//     // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
//                 ,        ,        ,        ,        ,        ,                                   ,        ,        ,        ,        ,        ,
//     // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
//                 ,        ,        ,        ,        ,        ,                                   ,        ,        ,        ,        ,        ,
//     // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
//                 ,        ,        ,        ,        ,        ,        ,                 ,        ,        ,        ,        ,        ,        ,
//     // └────────┴────────┴────────┴────┬───┴────┬───┴────┬───┴────┬───┘        └────┬───┴────┬───┴────┬───┴────┬───┴────────┴────────┴────────┘
//                                                 ,        ,        ,                          ,        ,
//                                     // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
//   ),
    [1] = LAYOUT( //RAI
        KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_LPRN, KC_RPRN, KC_AMPR, KC_P1, KC_P2, KC_P3, KC_EQL, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_LCBR, KC_RCBR, KC_PIPE, KC_P4, KC_P5, KC_P6, KC_MINS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_EXLM, KC_P7, KC_P8, KC_P9, KC_BSLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P0
    ),
    [2] = LAYOUT( //LWR
        KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_ENT, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_NO, KC_NO, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LALT, KC_NO, KC_N, KC_M, KC_NO, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_SPC, KC_F1, KC_CAPS, TO(0), KC_NO
    ),
    [3] = LAYOUT( //ADJ
        KC_NO, QK_BOOT, EE_CLR, KC_PWR, KC_SLEP, KC_WAKE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, UG_TOGG, UG_NEXT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPRV, KC_MNXT, KC_VOLU, KC_NO, KC_NO, RGB_TOG, RGB_MOD, UG_HUEU, UG_SATU, UG_VALU, KC_NO, KC_MUTE, KC_MSTP, KC_MPLY, KC_VOLD, KC_NO, NK_TOGG, KC_NO, KC_NO, BL_TOGG, BL_STEP, UG_HUED, UG_SATD, UG_VALD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TL_LOWR
    )


    /*
    [_EMPTY] = LAYOUT_kc(
    // ┌────────┬────────┬────────┬────────┬────────┬────────┐                          ┌────────┬────────┬────────┬────────┬────────┬────────┐
                ,        ,        ,        ,        ,        ,                                   ,        ,        ,        ,        ,        ,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
                ,        ,        ,        ,        ,        ,                                   ,        ,        ,        ,        ,        ,
    // ├────────┼────────┼────────┼────────┼────────┼────────┤                          ├────────┼────────┼────────┼────────┼────────┼────────┤
                ,        ,        ,        ,        ,        ,                                   ,        ,        ,        ,        ,        ,
    // ├────────┼────────┼────────┼────────┼────────┼────────┼────────┐        ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
                ,        ,        ,        ,        ,        ,        ,                 ,        ,        ,        ,        ,        ,        ,
    // └────────┴────────┴────────┴────┬───┴────┬───┴────┬───┴────┬───┘        └────┬───┴────┬───┴────┬───┴────┬───┴────────┴────────┴────────┘
                                                ,        ,        ,                          ,        ,
                                    // └────────┴────────┴────────┘                 └────────┴────────┴────────┘
    ),
    */
    
};



// 6 RGB underglow LEDs per half (12 total)
// Per-key RGB LEDs


// set custom indicators like an LED for caps lock, or layer indication
// bool rgb_matrix_indicators_user(void) {
//     if (!rgb_matrix_indicators_user()) {
//         return false;
//     }
//     rgb_matrix_set_color(index, red, green, blue);
//     return true;
// }
// // advanced indicator functions, a special macro to make easier to use
// bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
//     RGB_MATRIX_INDICATOR_SET_COLOR(index, red, green, blue);
//     return false;
// }

// layer indicator on all keys
// bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
//     for (uint8_t i = led_min; i < led_max; i++) {
//         switch(get_highest_layer(layer_state|default_layer_state)) {
//             case 3:
//                 rgb_matrix_set_color(i, RGB_RED);
//                 break;
//             case 2:
//                 rgb_matrix_set_color(i, RGB_BLUE);
//                 break;
//             case 1:
//                 rgb_matrix_set_color(i, RGB_YELLOW);
//                 break;
//             case 0:
//                 rgb_matrix_set_color(i, RGB_GREEN);
//                 break;
//             default:
//                 rgb_matrix_set_color(i, RGB_PURPLE);
//                 break;
//         }
//     }
//     return false;
// }

// when using WS2812 hsv is important because it allows the brightness to be limited, should change this to a switch.case
bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    HSV hsv = {0, 255, 255};

    switch (layer_state_is(2)) {

        default:
            break;
    }


    if (layer_state_is(2)) {//layer_state, 
        hsv = (HSV){130, 255, 255};
    } else {
        hsv = (HSV){30, 255, 255};
    }

    if (hsv.v > rgb_matrix_get_val()) {
        hsv.v = rgb_matrix_get_val();
    }
    RGB rgb = hsv_to_rgb(hsv);

    for (uint8_t i = led_min; i < led_max; i++) {
        if (HAS_ANY_FLAGS(g_led_config.flags[i], 0x02)) { // 0x01 == LED_FLAG_MODIFIER
            rgb_matrix_set_color(i, rgb.r, rgb.g, rgb.b);
        }
    }
    return false;
}
// can use this to only light up the caps lock key
// bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
//     if (host_keyboard_led_state().caps_lock) {
//         RGB_MATRIX_INDICATOR_SET_COLOR(5, 255, 255, 255); // assuming caps lock is at led #5
//     } else {
//         RGB_MATRIX_INDICATOR_SET_COLOR(5, 0, 0, 0);
//     }
//     return false;
// }



// uint32_t layer_state_set_user(uint32_t state) {
//     uint8_t layer = biton32(state);
//     switch(layer){
//         case _QUERTY: // 0-th layer
//         break;
//         case 
//     }
// }
